import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'fee_challans'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.uuid('id').primary().defaultTo(this.db.rawQuery('gen_random_uuid()').knexQuery)

      // Foreign keys
      table.uuid('school_id').references('schools.id').onDelete('CASCADE').notNullable()
      table.uuid('student_id').references('students.id').onDelete('CASCADE').notNullable()
      table
        .uuid('academic_year_id')
        .references('academic_years.id')
        .onDelete('CASCADE')
        .notNullable()
      table.uuid('enrollment_id').references('enrollments.id').onDelete('SET NULL')

      // Challan identification
      table.string('challan_number', 50).notNullable()
      table.string('period', 20).notNullable() // e.g., "2024-01" for January 2024, "2024-Q1" for Q1

      // Dates
      table.date('issue_date').notNullable()
      table.date('due_date').notNullable()

      // Amounts
      table.decimal('total_amount', 14, 2).notNullable()
      table.decimal('discount_amount', 14, 2).defaultTo(0)
      table.decimal('late_fee_amount', 14, 2).defaultTo(0)
      table.decimal('net_amount', 14, 2).notNullable() // total - discount + late_fee
      table.decimal('paid_amount', 14, 2).defaultTo(0)
      table.decimal('balance_amount', 14, 2).notNullable() // net - paid

      // Status
      table.string('status', 20).notNullable().defaultTo('pending') // pending, partial, paid, cancelled, overdue

      // Late fee tracking
      table.boolean('late_fee_applied').defaultTo(false)
      table.timestamp('late_fee_applied_at')

      // Notes
      table.text('remarks')

      // Generated by
      table.uuid('generated_by').references('users.id').onDelete('SET NULL')

      // Timestamps
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at')

      // Unique constraint: one challan per student per period per year
      table.unique(['school_id', 'challan_number'])
      table.unique(['student_id', 'academic_year_id', 'period'])

      // Indexes for faster queries
      table.index(['school_id', 'status'])
      table.index(['school_id', 'due_date'])
      table.index(['student_id', 'status'])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
